get http://localhost:8080/api/word-pairs

###

post http://localhost:8080/api/word-pairs
Content-Type: application/json

{
    "finnish_word": "testi neljä",
    "english_word": "test four"
}

###

delete http://localhost:8080/api/word-pairs/28

###

put http://localhost:8080/api/word-pairs/20
Content-Type: application/json

{
    "finnish_word": "päivitettySanaSuomi",
    "english_word": "UpdatedWordEnglish"
}

###

