get http://localhost:8080/api/word-pairs

###

post http://localhost:8080/api/word-pairs
Content-Type: application/json

{
    "finnish_word": "testi kolme23",
    "english_word": "test three"
}

###

delete http://localhost:8080/api/word-pairs/23

###

put http://localhost:8080/api/word-pairs/20
Content-Type: application/json

{
    "finnish_word": "päivitettySanaSuomi1",
    "english_word": "UpdatedWordEnglish"
}

###

